common/protob: fix multiple instances of enum in one message
Without this fix the type is defined multiple times which irritates
mypy:

src/trezor/messages/ApplySettings.py:10: error: Cannot assign multiple types to name "EnumTypeSafetyCheckLevel" without an explicit "Type[...]" annotation  [misc]